### ISSUE TITLE
NullPointerException when udpating to aura framework 0.3343

### ISSUE THREAD

**Issue by Jerrkawz** [forcedotcom/aura-note#8]
I was not able to run aura-note as packaged, because it was complaining about not being able to find the aura version specified. After updating aura framework version to 0.3343 in pom.xml I was able to build and start the server but i get the following exception when trying to access the component

Invalid converter not registered : org.auraframework.util.type.BadConverter@57b25438
2015-12-01 16:02:36 ERROR ExceptionAdapterImpl:115 - Unhandled Exception 'null'
java.lang.NullPointerException
	at org.auraframework.impl.adapter.ServletUtilAdapterImpl.getClientLibraryUrls(ServletUtilAdapterImpl.java:320)
	at org.auraframework.impl.adapter.ServletUtilAdapterImpl.getStyles(ServletUtilAdapterImpl.java:299)
	at org.auraframework.impl.adapter.format.html.BaseComponentDefHTMLFormatAdapter.write(BaseComponentDefHTMLFormatAdapter.java:65)
	at org.auraframework.impl.adapter.format.html.BaseComponentDefHTMLFormatAdapter.write(BaseComponentDefHTMLFormatAdapter.java:45)
	at org.auraframework.impl.SerializationServiceImpl.write(SerializationServiceImpl.java:96)
	at org.auraframework.http.AuraServlet.internalGet(AuraServlet.java:301)
	at org.auraframework.http.AuraServlet.doGet(AuraServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1366)
	at org.auraframework.http.AuraTestFilter.doFilter(AuraTestFilter.java:254)
	at org.auraframework.http.AuraContextFilter.doFilter(AuraContextFilter.java:100)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1337)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:520)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:271)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:98)
	at org.auraframework.http.AuraRewriteFilter.doFilter(AuraRewriteFilter.java:86)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1337)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:520)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:346)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mleonardsfdc** [comment]
This sample app is out-of-date and is no longer maintained. To get started with Aura, see the [Aura Open Source Developer Guide](https://github.com/forcedotcom/aura/blob/master/aura_oss.pdf).

I'm closing out this issue.
